controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

# Route pour la page de création
admin_create:
    path: /admin/create
    controller: App\Controller\AdminController::create

# Route pour la page de mise à jour
update:
    path: /admin/update/{id}
    controller: App\Controller\AdminController::update
    requirements:
        id: \d+  # Assurez-vous que l'id soit un nombre entier

# Route pour la page de suppression
delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::delete
    requirements:
        id: \d+  # Assurez-vous que l'id soit un nombre entier

admin_search:
    path: /admin/search
    controller: App\Controller\AdminController::searchByName

# config/routes.yaml

# Route pour la page d'accueil
app_demande_index:
    path: /demande
    controller: App\Controller\DemandeController::index
    methods: GET

# Route pour afficher les statistiques
app_demands_statistics:
    path: /demande/statistics
    controller: App\Controller\DemandeController::statisticsAction
    methods: GET

# Route pour la création d'une nouvelle demande
app_demande_new:
    path: /demande/new
    controller: App\Controller\DemandeController::new
    methods: [GET, POST]

# Route pour afficher une demande spécifique
app_demande_show:
    path: /demande/{id}
    controller: App\Controller\DemandeController::show
    methods: GET
    requirements:
        id: \d+  # Cela garantit que l'ID est un nombre entier

# Route pour modifier une demande existante
app_demande_edit:
    path: /demande/{id}/edit
    controller: App\Controller\DemandeController::edit
    methods: [GET, POST]
    requirements:
        id: \d+  # Cela garantit que l'ID est un nombre entier

# Route pour supprimer une demande
app_demande_delete:
    path: /demande/{id}
    controller: App\Controller\DemandeController::delete
    methods: POST
    requirements:
        id: \d+  # Cela garantit que l'ID est un nombre entier

